//
//  InvoiceRepository.swift
//  alpha
//
//  Created by Claude Code on 12/18/24.
//

import Foundation
import Supabase

class InvoiceRepository {
    private let supabase = SupabaseClientManager.shared.client
    private let ownershipResolver = OwnershipResolver()

    func fetchInvoices(
        status: String? = nil,
        clientId: String? = nil,
        limit: Int = 100,
        offset: Int = 0
    ) async throws -> [Invoice] {
        let scope = try await ownershipResolver.currentScope()
        var query = supabase
            .from("invoices")
            .select("""
                *,
                client:clients(*),
                project:projects(*),
                line_items:invoice_line_items(*)
            """)

        // Apply filters first, before order and range
        if let status = status {
            query = query.eq("status", value: status.lowercased())
        }

        if let clientId = clientId {
            query = query.eq("client_id", value: clientId)
        }

        if let organizationId = scope.organizationId {
            query = query.eq("organization_id", value: organizationId)
        } else {
            query = query.eq("user_id", value: scope.userId)
        }

        // Then apply order, range, and execute (don't reassign)
        let response = try await query
            .order("due_date")
            .range(from: offset, to: offset + limit - 1)
            .execute()

        let invoices: [Invoice] = try JSONDecoder().decode([Invoice].self, from: response.data)
        return invoices
    }

    func createInvoice(
        clientId: String,
        projectId: String?,
        dueDate: Date,
        lineItems: [InvoiceLineItemCreate],
        taxRate: Double?,
        notes: String?,
        currency: String
    ) async throws -> Invoice {
        let scope = try await ownershipResolver.currentScope()
        // Calculate totals using percent semantics (e.g. 8.25 means 8.25%)
        let subtotal = lineItems.reduce(0) { $0 + ($1.quantity * $1.rate) }
        let normalizedTaxRate = taxRate ?? 0
        let taxAmount = subtotal * (normalizedTaxRate / 100)
        let total = subtotal + taxAmount

        // Insert invoice (invoice_number auto-generated by trigger when omitted)
        let invoiceInsert = InvoiceInsert(
            organizationId: scope.organizationId,
            userId: scope.organizationId == nil ? scope.userId : nil,
            clientId: clientId,
            projectId: projectId,
            invoiceNumber: nil,
            issueDate: Date().iso8601String,
            dueDate: dueDate.iso8601String,
            subtotal: subtotal,
            taxRate: normalizedTaxRate,
            taxAmount: taxAmount,
            total: total,
            currency: currency,
            status: InvoiceStatus.draft.rawValue,
            notes: notes
        )

        let invoiceResponse = try await supabase
            .from("invoices")
            .insert(invoiceInsert)
            .select()
            .single()
            .execute()

        let invoice: Invoice = try JSONDecoder().decode(Invoice.self, from: invoiceResponse.data)

        // Insert line items
        for (index, item) in lineItems.enumerated() {
            let lineItemInsert = InvoiceLineItemInsert(
                invoiceId: invoice.id,
                description: item.description,
                quantity: item.quantity,
                rate: item.rate,
                order: index
            )

            try await supabase
                .from("invoice_line_items")
                .insert(lineItemInsert)
                .execute()
        }

        // Fetch complete invoice with line items
        return try await fetchInvoice(id: invoice.id)
    }

    func fetchInvoice(id: String) async throws -> Invoice {
        let response = try await supabase
            .from("invoices")
            .select("""
                *,
                client:clients(*),
                project:projects(*),
                line_items:invoice_line_items(*)
            """)
            .eq("id", value: id)
            .single()
            .execute()

        let invoice: Invoice = try JSONDecoder().decode(Invoice.self, from: response.data)
        return invoice
    }

    func updateInvoiceStatus(id: String, status: String, paidAt: Date? = nil) async throws -> Invoice {
        var updateData: [String: AnyJSON] = ["status": try AnyJSON(status.lowercased())]

        if let paidAt = paidAt {
            updateData["paid_at"] = try AnyJSON(paidAt.iso8601String)
        }

        let response = try await supabase
            .from("invoices")
            .update(updateData)
            .eq("id", value: id)
            .select("""
                *,
                client:clients(*),
                project:projects(*),
                line_items:invoice_line_items(*)
            """)
            .single()
            .execute()

        let invoice: Invoice = try JSONDecoder().decode(Invoice.self, from: response.data)
        return invoice
    }

    func markAsPaid(id: String) async throws -> Invoice {
        return try await updateInvoiceStatus(id: id, status: InvoiceStatus.paid.rawValue, paidAt: Date())
    }

    func sendInvoice(id: String) async throws -> Invoice {
        return try await updateInvoiceStatus(id: id, status: InvoiceStatus.sent.rawValue)
    }
}

struct InvoiceLineItemCreate {
    let description: String
    let quantity: Double
    let rate: Double
}

// MARK: - Insert DTOs

struct InvoiceInsert: Codable {
    let organizationId: String?
    let userId: String?
    let clientId: String?
    let projectId: String?
    let invoiceNumber: String?
    let issueDate: String
    let dueDate: String
    let subtotal: Double
    let taxRate: Double
    let taxAmount: Double
    let total: Double
    let currency: String
    let status: String
    let notes: String?

    enum CodingKeys: String, CodingKey {
        case organizationId = "organization_id"
        case userId = "user_id"
        case clientId = "client_id"
        case projectId = "project_id"
        case invoiceNumber = "invoice_number"
        case issueDate = "issue_date"
        case dueDate = "due_date"
        case subtotal
        case taxRate = "tax_rate"
        case taxAmount = "tax_amount"
        case total
        case currency
        case status
        case notes
    }
}

struct InvoiceLineItemInsert: Codable {
    let invoiceId: String
    let description: String
    let quantity: Double
    let rate: Double
    let order: Int

    enum CodingKeys: String, CodingKey {
        case invoiceId = "invoice_id"
        case description
        case quantity
        case rate
        case order
    }
}
