"""add_password_to_users

Revision ID: 08114f16cfa2
Revises: 3bed9f6f8db6
Create Date: 2025-09-12 00:42:54.643024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08114f16cfa2'
down_revision = '3bed9f6f8db6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###