"""Add pricing fields to time entries model

Revision ID: 25abd9729fc2
Revises: 66a033e149d0
Create Date: 2025-09-22 16:47:43.717045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25abd9729fc2'
down_revision = '66a033e149d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('calculated_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('time_entries', sa.Column('calculated_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('time_entries', sa.Column('pricing_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('time_entries', sa.Column('applied_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('time_entries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'created_at')
    op.drop_column('time_entries', 'applied_rules')
    op.drop_column('time_entries', 'pricing_context')
    op.drop_column('time_entries', 'calculated_amount')
    op.drop_column('time_entries', 'calculated_rate')
    # ### end Alembic commands ###