"""Add created_at to projects table

Revision ID: 63c0a117427c
Revises: 08114f16cfa2
Create Date: 2025-09-12 18:43:58.450422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c0a117427c'
down_revision = '08114f16cfa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###