"""Add calculated pricing fields to time entries

Revision ID: 66a033e149d0
Revises: 854a0cd1d3c4
Create Date: 2025-09-22 16:47:01.090997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a033e149d0'
down_revision = '854a0cd1d3c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###