"""Add address fields for PDF generation

Revision ID: 854a0cd1d3c4
Revises: 63c0a117427c
Create Date: 2025-09-22 15:41:55.055687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854a0cd1d3c4'
down_revision = '63c0a117427c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'address')
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###